name: Release

on:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags like v1.0.0, v1.2.3, etc.

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Run tests (if any)
        run: npm test --if-present

      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Get previous tag
        id: get_previous_tag
        run: |
          PREVIOUS_TAG=$(git tag -l --sort=-version:refname | grep -v "^${{ steps.get_version.outputs.VERSION }}$" | head -n 1)
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "PREVIOUS_TAG=HEAD~10" >> $GITHUB_OUTPUT
            # Check if HEAD~10 exists
            if git rev-parse --verify HEAD~10 >/dev/null 2>&1; then
              echo "PREVIOUS_TAG=HEAD~10" >> $GITHUB_OUTPUT
              echo "No previous tag found, using HEAD~10 for comparison"
            else
              # Use the initial commit hash
              INITIAL_COMMIT=$(git rev-list --max-parents=0 HEAD)
              echo "PREVIOUS_TAG=$INITIAL_COMMIT" >> $GITHUB_OUTPUT
              echo "No previous tag found and not enough commits for HEAD~10, using initial commit $INITIAL_COMMIT for comparison"
            fi
          else
            echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
            echo "Previous tag: $PREVIOUS_TAG"
          fi

      - name: Verify package version matches tag
        run: |
          PACKAGE_VERSION="v$(node -p "require('./package.json').version")"
          TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "❌ Package version ($PACKAGE_VERSION) doesn't match tag ($TAG_VERSION)"
            exit 1
          fi
          echo "✅ Package version matches tag: $TAG_VERSION"

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Changes in ${{ steps.get_version.outputs.VERSION }}

            🚀 **smooth-auto-scroll** has been updated!

            ### Installation
            ```bash
            npm install smooth-auto-scroll@${{ steps.get_version.outputs.VERSION }}
            ```

            ### Demo
            Try the interactive demo: https://marcderhammer.github.io/smooth-auto-scroll/

            ### Full Changelog
            See all changes: https://github.com/marcderhammer/smooth-auto-scroll/compare/${{ steps.get_previous_tag.outputs.PREVIOUS_TAG }}...${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.VERSION, '-') }}
          generate_release_notes: true
